global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
         aw_server_name: ci 

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
         aw_server_name: ci-server-containers

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
         aw_server_name: ci-server-prometheus

  - job_name: 'awm4lnodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-35-154-28-253.ap-south-1.compute.amazonaws.com:9100']
        labels:
         aw_server_name: awm4l

  - job_name: 'gkdevasnodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-35-154-19-183.ap-south-1.compute.amazonaws.com:9100']
        labels:
         aw_server_name: gkdev
